### ISSUE TITLE
Active Directory configuration

### ISSUE THREAD

**Issue by dbr1337** [sdelements/lets-chat#261]
Hello,
i need to implement the Users from Active Directory to XMPP but it will not work.
This is my configuration:

```
auth:
  ldap:
    connect_settings:
      url: ldap://ldap.censored.com
      tlsOptions:
        ca: cert.pem
    server_certs: []
    bind_options:
      bindDN: CN=Jabber Testuser,CN=Users,DC=censored,DC=com
      bindCredentials:
    search:
      base: CN=Users,DC=censored,DC=com
      opts:
        scope: one
        filter: (uid={{mail}})
        attributes: []
    field_mappings:
      uid: uid 3 LDAP unique ID
      username: userPrincipalName # used for mention (@uid)
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail
```

```
xmpp:
  enable: true
  roomCreation: false
  debug:
    handled: false
    unhandled: true
  port: 5222
  host: 192.168.211.161
  tls:
    enable: true
    key: ./cert.key
    cert: ./cert.crt
```
Can anyone please help me?

**Comment by sibartlett** [comment]
```
uid: uid 3 LDAP unique ID
```

is supposed to be:

```
uid: uid # LDAP unique ID
```

**Comment by dbr1337** [comment]
auth:
  ldap:
    connect_settings:
      url: ldap://ldap.censored.com
      tlsOptions:
        ca: cert.pem
    server_certs: []
    bind_options:
      bindDN: CN=Jabber Testuser,CN=Users,DC=censored,DC=com
      bindCredentials:
    search:
      base: CN=Users,DC=censored,DC=com
      opts:
        scope: one
        filter: (uid={{sAMAccountName}})
        attributes: []
    field_mappings:
      uid: uid
      username: sAMAccountName # used for mention (@uid)
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail

Dont work

**Comment by hhaidar** [comment]
Try changing:

`CN=Jabber Testuser,CN=Users,DC=censored,DC=com`

to

`CN=Jabber\ Testuser,CN=Users,DC=censored,DC=com`

**Comment by sibartlett** [comment]
Try this one: 

```
auth:
  ldap:
    connect_settings:
      url: ldap://ldap.censored.com
      tlsOptions:
        ca: cert.pem
    server_certs: []
    bind_options:
      bindDN: CN=Jabber Testuser,CN=Users,DC=censored,DC=com
      bindCredentials:
    search:
      base: CN=Users,DC=censored,DC=com
      opts:
        scope: one
        filter: (uid={{username}})
        attributes: []
    field_mappings:
      uid: uid
      username: sAMAccountName # used for mention (@uid)
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail
```

**Comment by scragg0x** [comment]
I got mine working with AD.

Firstly, make sure you update the ldap plugin because I recently submitted a patch that fixed a breaking bug when it came to creating user via ldap auth.

here is what my settings look like:

```
auth:
  providers: [ldap]
  ldap:
    connect_settings:
      url: ldap://my.ldap.server:389
    server_certs: []
    bind_options:
      bindDN: "CN=Jabber Testuser,CN=Users,DC=censored,DC=com"
      bindCredentials: 
    search:
      base: "CN=Users,DC=censored,DC=com"
      opts:
        scope: one
        filter: (sAMAccountName={{username}})
        attributes: []
    field_mappings:
      uid: sAMAccountName
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail
```

Using your DN as an example.  BTW, I'm no AD admin but you can try OU=Users instead of CN=Users.  Not sure though, you could have it correct there.

**Comment by sibartlett** [comment]
@scragg0x I'm going to add your LDAP config to the plugin's readme file as an example, if you don't mind?

**Comment by scragg0x** [comment]
@sibartlett That's fine, I hope it helps.  I don't really don't know much about AD so I had to talk to our admin.  It would be helpful to highlight some of the fields that will need to be changed, such as 

ldap url
server_certs (if used)
bindDN
bindCredentials
search.base

Everything else should match my example.

**Comment by dbr1337** [comment]
@scragg0x Thank you, but it doesnt will work.
This is my configuration actually:
auth:
  ldap:
    connect_settings:
      url: ldap://ldap.censored.com:389
      tlsOptions:
        ca: cert.pem
    server_certs: []
    bind_options:
      bindDN: OU=Users,DC=censored,DC=com
      bindCredentials:
    search:
      base: OU=Users,DC=censored,DC=com
      opts:
        scope: one
        filter: (sAMAccountName={{username}})
        attributes: []
    field_mappings:
      uid: sAMAccountName
      firstName: givenName
      lastName: sn
      displayName: givenName
      email: mail

**Comment by sibartlett** [comment]
@dbr1337 I've updated the examples in the [LDAP plugin README](https://github.com/sdelements/lets-chat-ldap). Maybe they are more useful?

**Comment by dbr1337** [comment]
I tried the examples, but i get these errors:
http://img-host.de/bild.php/53992,bildschirmfoto20150218um1011169YU2V.png

**Comment by dbr1337** [comment]
Now i works! :dancer:
But i have a new question: How can i import the Groups and all Users from AD to XMPP?

**Comment by sibartlett** [comment]
We don't currently support importing users from LDAP, nor do we currently support XMPP rosters.

We're hoping to add support for XMPP rosters and private chat in the next major release.

You can enable TLS for XMPP using the following config settings:

```
xmpp:
  tls:
    enable: true
    key: ./server.key
    cert: ./server.crt
```

If you're using HTTPS, you can use the same certificate and key. There's no need to change the port.
