### ISSUE TITLE
EADDRNOTAVAIL when setting host with docker

### ISSUE THREAD

**Issue by bufke** [sdelements/lets-chat#465]
I'm trying to set the host so that I can use xmpp (based on https://github.com/sdelements/lets-chat/issues/302). When set to 0.0.0.0 the web interface works fine while xmpp does not. When I set to the correct domain I get

```
app_1 | 
app_1 | events.js:72
app_1 |         throw er; // Unhandled 'error' event
app_1 |               ^
app_1 | Error: listen EADDRNOTAVAIL
app_1 |     at errnoException (net.js:905:11)
app_1 |     at Server._listen2 (net.js:1024:19)
app_1 |     at listen (net.js:1065:10)
app_1 |     at net.js:1147:9
app_1 |     at asyncCallback (dns.js:68:16)
app_1 |     at Object.onanswer [as oncomplete] (dns.js:121:9)
```

I'm using docker-compose with the provided fig.yml file.

**Comment by bufke** [comment]
As a workaround I was able to run without docker - just running node and mongo locally.

**Comment by hhaidar** [comment]
Is this still an issue?

**Comment by bufke** [comment]
I updated to 0.4.0 and tried again. Same settings as a known working instance (without docker). Instead of getting an error I get no output now.

app_1 | 
app_1 | > lets-chat@0.4.0 prestart /usr/src/app
app_1 | > migroose
app_1 | 

I will play around with it more latter. Settings file http://pastebin.com/VGAVxVDq

**Comment by sibartlett** [comment]
Hi @bufke,

Could you try our new official Docker image? It's available on Docker Hub here: https://registry.hub.docker.com/u/sdelements/lets-chat/

Thanks

**Comment by bufke** [comment]
I tried the new one. Sorry it took so long. If this only affect me feel free to close since I'm happy with not using docker. But in the interest of making this easier for others:

```
app_1   | Release 0.4.0
app_1   | 
app_1   | events.js:85
app_1   |       throw er; // Unhandled 'error' event
app_1   |             ^
app_1   | Error: listen EADDRNOTAVAIL
app_1   |     at exports._errnoException (util.js:746:11)
app_1   |     at Server._listen2 (net.js:1139:19)
app_1   |     at listen (net.js:1182:10)
app_1   |     at net.js:1280:9
app_1   |     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
app_1   |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

docker-compose.yml
```
app:
  image: sdelements/lets-chat
  links:
    - mongo
  volumes:
    - ./certs:/opt/certs
  ports:
    - 5000:5000
    - 5001:5001
    - 5222:5222
  environment:
    LCB_HTTP_ENABLE: true
    LCB_HTTP_HOST: 'chat.mydomain.com'
    LCB_HTTP_PORT: 5000
    LCB_HTTPS_ENABLE: false
    LCB_HTTPS_PORT: 5001
    LCB_HTTPS_KEY: key.pem
    LCB_HTTPS_CERT: certificate.pem
    LCB_XMPP_ENABLE: true
    LCB_XMPP_ROOM_CREATION: false
    LCB_XMPP_PORT: 5222
    LCB_XMPP_HOST: 'chat.mydomain.com'
    LCB_XMPP_TLS_ENABLE: true
    LCB_XMPP_TLS_KEY: /opt/certs/server.key
    LCB_XMPP_TLS_CERT: /opt/certs/server.crt
    LCB_ROOMS_PRIVATE: true


mongo:
  image: mongo:latest
```

When I remove the environment variables it works in the web interface as expected.
