### ISSUE TITLE
Question about docker image

### ISSUE THREAD

**Issue by chiel1980** [sdelements/lets-chat#535]
Hi,

I do a git pull from time to time and saw that the default port from 5000 changed to 8080 and that the Dockerfile is now in a directory 'docker'.
Those were easy to fix but I was wondering why the port has changed?
Also, it seems my settings.yml is not read anymore when I rebuild the image and container..everyone can register since I've configured that to false in my settings.yml (enableRegistration false).
I rebuild the image with: docker-compose build --no-cache && docker-compose up

Is the location also changed where I need to drop my settings.yml ?

My settings.yml in the lets-chat folder::

```
#
# Let's Chat Settings
#
# See defaults.yml for all available options
#

env: production # development / production

http:
  enable: true
  host: 'localhost'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

xmpp:
  enable: false
  port: 5222
  domain: example.com

database:
  uri: mongodb://localhost/letschat

secrets:
  cookie: secretsauce

files:
  enable: true
  provider: local
  maxFileSize: 100000000
  restrictTypes: true
  allowedTypes:
    - 'image/jpeg'
    - 'image/png'
    - 'image/gif'
  local:
    dir: uploads

auth:
  throttling:
    enable: true
    threshold: 3
  providers: [local] # [local, kerberos, ldap] - You can specify the order
  local:
    enableRegistration: false
    passwordRegex: ^.{8,64}$

private:
  enable: true
  roster: online # online / all
  expire: 360 # false or number of minutes

noRobots: true # Serve robots.txt with disallow

rooms:
  private: true
```
