### ISSUE TITLE
Problems to upload PDF

### ISSUE THREAD

**Issue by janstieler** [sdelements/lets-chat#719]
Hi,
I have problems to upload pdf-files to my lets-chat installation.
I got only the message `ops, something went wrong` this is not really a helpfull information to solve the problem :).
My settings.yml for files is:
```
files:
  enable: true
  provider: local
  restrictTypes: true
  allowedTypes:
    - 'image/jpeg'
    - 'image/png'
    - 'image/gif'
    - 'application/pdf'
  local:
    dir: uploads
```
Or where can I find a better log for problem solving?

Cheers
