### ISSUE TITLE
Where is the file upload function?

### ISSUE THREAD

**Issue by enrichz** [sdelements/lets-chat#721]
Hello,
I installed lets chat in local on my node server and I'm not able to find the feature for uploading files. Is it a plugin or something?

Thanks

**Comment by Cyberwizzard** [comment]
In your settings.yml, make sure you have:
```
files:
  enable: true
  provider: local
  local:
    dir: uploads
```

Make sure to expand the right sidebar by pressing the arrow button in the top-right. There should be a section saying "Files". The plus button there allows you to upload files.
